### ISSUE TITLE
PreciousStones doesn't know how to handle /ps info.

### ISSUE THREAD

**Issue by UnusualToast** [phaed420/PreciousStones#778]
Throwing this (http://pastebin.com/V3BFrwYB) in the console.

Steps to reproduce:
Place a PreciousStones block to create a protected area
Use /ps info to show the information of the area you just created
Remove the protection block
Use /ps info again, waiting for the "No fields found." message.
Get "Command not recognized" message + error in the console

Using latest version from BukkitDev (9.7.1, Dec. 26)

**Comment by phaed420** [comment]
Try the latest version from Jenkins.

**Comment by UnusualToast** [comment]
This should be the latest one...? http://repo.sacredlabyrinth.net:8080/job/PreciousStones/410/ Dec. 12th, the one from DevBukkit is from Dec. 26th.

**Comment by phaed420** [comment]
Yep try that one, let me know if problem persists.

**Comment by UnusualToast** [comment]
Yes it does. All three of the bugs.

**Comment by phaed420** [comment]
Try the new build.

**Comment by UnusualToast** [comment]
#411 from Jenkins (/version preciousstones returns "9.7.1-SNAPSHOT"), still the same issue.

**Comment by spetznack** [comment]
Using latest PreciousStones version from bukkitdev (9.7.1) is not throwing me this error when using the /ps info command. I only tried to use the command with permission node for /ps info set to true. 

Using Spigot 1.8 #22

What server version are you using @UnusualToast ?

**Comment by UnusualToast** [comment]
Spigot 1.8. Not sure what you mean with build #, though. Well, I don't remember setting up permissions, although I'm OP. Would that be it?

**Comment by spetznack** [comment]
I mentioned what BuildTools - build # that worked with me, which is Build #22 (latest at the time I'm writing this)
You can find the different builds from their jenkins: https://hub.spigotmc.org/jenkins/job/BuildTools/

You may have used the bash code to download the last successeful build (bash code can be found here http://www.spigotmc.org/threads/buildtools-updates-information.42865/)? In that case I have no idea how to tell what build you are using. I guess if I were you I would try getting the latest build today, or at least #22, because that version worked for me.. 

There is no guarantee this has to do with server versions though, I also tried as OP as well as having the preciousstones.admin.* permission set to true for me. 

Hmm.. Other than that I have no idea why it would work for me and not you :s Did you fetch the latest Vault version? If all fails, I thinkg I would try starting a clean new server and install only PreciousStones and Vault. If that doesn't throw the error, I would then try moving in parts of the actual server (that threw the error) and see when the error appears.

Good luck!

**Comment by UnusualToast** [comment]
BuildTools # has nothing to do with Spigot version.

I didn't think of Vault either. Although I remember downloading its latest version, I will try that again later.

**Comment by spetznack** [comment]
Aha, I completely misunderstood how the buildtools worked. I thought every new buildtools build included the newest spigot\craftbukkit\bukkit build >.< 

Sorry about that, it was a stupid assumption o.o

Spigot version that worked for me: git-Spigot-b8f6402-a646500

**Comment by MuroHasegawa** [comment]
I'm having the same issue as you @UnusualToast not to sure why.

I'm using a dev build of 1.7.10 Bukkit (Managed to grab it before the lawsuit :D)
And yes I've got the 9.7.1 snapshot, Vault is updated.  --->  http://pastebin.com/hcHEL3V8

Also on a side note: City protection doesn't notify players that they are entering or leaving a protection field. No errors in console. (Could also be something on my end...)
