### ISSUE TITLE
UUID

### ISSUE THREAD

**Issue by krustymk** [phaed420/PreciousStones#786]
Until this is fixed (copied link from comments section, not mine)

http://www.spigotmc.org/resources/mypreciousstone.3290/

**Comment by frizzbee30** [comment]
yes, we have same issue, 1 user has changed their name and is unable to access their field now. This is a 'game breaker' with the ability to change names in minecraft now functional!

**Comment by spetznack** [comment]
phaed has a lot on his plate with this plugin, and the plate is being filled almost daily with requests\issues. It's obvious that this is a issue and phaed know this very well, so please avoid confirming that this is still a issue. This issue is here to find a solution, if you know a thing or two about how to use the UUID API --> and if you have ideas for how exactly the preciousstones database can be updated to work with UUID's then please share it and or possibly make a commit? 

Thanks for listening

**Comment by krustymk** [comment]
Suddenly im having difficulty thinking of the name for a male chicken.... and why on earth that popped into my head is beyond me... hmmm rooster... nope thats not it.. any feedback on that issue speckledsack?

**Comment by optical** [comment]
+1 - This is a major issue now with name changes being live.

**Comment by batkins62** [comment]
Need a fix, players are getting unhappy noticing that they cant access there stuff

**Comment by phaed420** [comment]
Latest dev version has uuid fix

**Comment by frizzbee30** [comment]
Really appreciated!
