### ISSUE TITLE
Command-on enter/exit changing worlds (nether) bug

### ISSUE THREAD

**Issue by krustymk** [phaed420/PreciousStones#788]
Ive mentioned this before but dont know if i didnt explain very well or it cant be fixed.
I have the following flags in my config, and if i go outside and back into the area normally (walking jumping running) it work great.

```
  command-on-enter:
  - fly {owner}
  command-on-exit:
  - fly {owner}
```
However! 
If i create a portal and go to the nether i can still fly in the nether, so i added
```
  ^prevent-portal-enter: true
  ^prevent-portal-create: true
  prevent-portal-destination: true
```
To stop players creating a portal inside the field with the fly command. But now if a player leaves the 'fly field and goes to the nether and then re-enters their area via a /home command the 'command-on-enter' doesnt fire.

I hope ive made this clear? lol
The problem this gives is that the fly command is now swapped ( the player can fly outside the field but not inside)

I hope

**Comment by phaed420** [comment]
Just tested this like this.  

```
  command-on-enter:
  - say "command enter"
  command-on-exit:
  - say "command exit"
```

When you enter into the nether "command exit" shows on chat, when you come back "command enter" shows.  It works as it should.  The problem here I believe is the fly plugin command which acts as a toggle and automatically disables flying when you cross into the nether.  So running the command again effectively toggles back on the flying in the nether.

You could ask the plugin author to add /fly on and /fly off commands so you can use them independently instead of a single toggle.
